# env
# ---
export PATH="$PATH:$HOME/.paps/bin"
export EDITOR='nvim'
export MANPAGER='nvim +Man!'
#export LESS='-RiM' # less config: colors, smart-case search, verbose prompt

# aliases
# -------
alias ls='ls --color=auto -F'
alias l='ls'
alias ll='ls -lh'
alias lll='ll'
alias llll='ll'
alias la='ls -lha'
alias sl='ls'
alias grep='grep --color=auto'
alias vim="echo 'choose between nvim and \\\vim' ; false"
alias vi="echo 'choose between nvim and \\\vim' ; false"
alias vimdiff="echo 'choose between nvim -d and \\\vimdiff' ; false"
alias del='trash-put'
alias rm="echo 'choose between del (trash-put) and \\\rm' ; false"

# history
# -------
# append history immediately, ignore duplicates and space-prefixed commands
setopt inc_append_history hist_ignore_dups hist_find_no_dups hist_ignore_space
HISTFILE="$HOME/.zsh_history"
HISTSIZE=30000  # max entries in memory
SAVEHIST=30000  # max entries written to file

# VCS info
# --------
autoload -Uz vcs_info
zstyle ':vcs_info:*' check-for-changes true
zstyle ':vcs_info:*' formats '%F{magenta}(%b%u%c)%f '
zstyle ':vcs_info:*' actionformats '%F{magenta}(%b|%a%u%c)%f '
zstyle ':vcs_info:*' stagedstr '+'
zstyle ':vcs_info:*' unstagedstr '*'
zstyle ':vcs_info:*' enable git
# refresh vcs info before each prompt
# (clobbers the entire precmd hook but it's fine, we just need this)
precmd() { vcs_info }

# completions
# -----------
autoload -Uz compinit
compinit
unsetopt correct_all
setopt correct # only correct commands, not arguments

# command line vim mode
# ---------------------
bindkey -v # vi mode
KEYTIMEOUT=1 # almost no delay (=10ms) when escape is pressed (lowest practical value)
# search bindings (must be after bindkey -v to not get overridden)
bindkey "^R" history-incremental-pattern-search-backward
bindkey "^S" history-incremental-pattern-search-forward
bindkey -M vicmd '?' history-incremental-pattern-search-backward
bindkey -M vicmd '/' history-incremental-pattern-search-forward
# visual mode goes to real vim
autoload -Uz edit-command-line
zle -N edit-command-line
bindkey -M vicmd 'v' edit-command-line

# prompt
# ------
setopt prompt_subst # allow variable expansion in PS1
# show [N] when in vi normal mode, nothing in insert mode
function zle-keymap-select zle-line-init {
	VI_MODE="${${KEYMAP/vicmd/[N] }/(main|viins)/}"
	zle reset-prompt
}
# register widgets to update vi mode indicator on keymap change and line init
zle -N zle-keymap-select
zle -N zle-line-init
# [N] ↪exit_code [user@host:]path
# vi mode indicator, exit code in red only if non-zero, user@host only when SSHed in, path in blue
if [[ -n "$SSH_CONNECTION" ]]; then
	PS1='${VI_MODE}%(?..%F{red}↪%?%f )${vcs_info_msg_0_}%F{green}%n%f@%F{yellow}%m%f:%B%F{blue}%~%f%b› '
else
	PS1='${VI_MODE}%(?..%F{red}↪%?%f )${vcs_info_msg_0_}%B%F{blue}%~%f%b› '
fi

# other stuff...
# --------------
setopt no_rm_star_silent # prompt for confirmation on rm *
stty -ixon # disable ctrl-s/ctrl-q terminal scroll lock (ultra legacy stuff that is just annoying)
setopt interactivecomments # allow for comments starting with # directly in the command line

# ssh-agent
# ---------
# only start ssh-agent on local sessions, not when SSHed in (-z tests if a string is zero-length)
if [[ -z "$SSH_CONNECTION" ]]; then
	local ssh_agent_env="$HOME/.ssh/environment-$HOST"
	function start_ssh_agent() {
		ssh-agent | sed 's/^echo/#echo/' > ${ssh_agent_env}
		chmod 600 ${ssh_agent_env}
		. ${ssh_agent_env} > /dev/null
		ssh-add
	}
	if [ -f "${ssh_agent_env}" ]; then
		. ${ssh_agent_env} > /dev/null
		ps x | grep ${SSH_AGENT_PID} | grep ssh-agent > /dev/null || {
			start_ssh_agent;
		}
	else
		start_ssh_agent;
	fi
	unfunction start_ssh_agent
	unset ssh_agent_env
fi

